version: '3'
services:
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=backendentregas"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgres/data
volumes:
  pg-data:
